services:
  - type: web
    name: white-whaling
    env: node
    buildCommand: npm install && npm run install:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
