services:
  - type: web
    name: white-whaling
    env: node
    branch: new_branch
    buildCommand: npm install && cd src && npm install && npm run build && cd .. && cd server && npm install && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        fromService:
          name: white-whaling
          type: web
          property: url
